import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, ArrowUpRight } from "lucide-react";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import StickyMobileCTA from "@/components/layout/StickyMobileCTA";
import Breadcrumb from "@/components/ui/Breadcrumb";
import { FYLKER } from "@/data/geografi";
export const metadata: Metadata = { title: "Fasade etter fylke – Finn fasadefirma i hele Norge", description: "Finn kvalifiserte fasadefirma i alle norske fylker. Oversikt over alle fylker og kommuner med lokale firma.", alternates: { canonical: "https://fasadeteknikk.no/fylke" } };
export default function FylkerOversikt() {
  return (<><Header /><main><div className="container-site pt-5 pb-2"><Breadcrumb items={[{ navn: "Fylker" }]} /></div><section className="hero-pattern"><div className="container-site py-10 sm:py-14 text-center"><div className="section-label">Geografisk dekning</div><h1 className="font-display font-extrabold text-display-xl text-neutral-900 mb-4 text-balance">Fasade i alle norske fylker</h1><p className="text-body-lg text-neutral-500 max-w-2xl mx-auto">Vi formidler tilbud fra kvalifiserte fasadefirma i hele Norge. Velg ditt fylke for å finne lokale fagfolk.</p></div></section><section className="section-white section-py-sm"><div className="container-site"><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{FYLKER.map(fylke => (<Link key={fylke.slug} href={`/fylke/${fylke.slug}`} className="card p-6 group"><div className="flex items-start justify-between gap-3"><div><h2 className="font-display font-bold text-heading-md text-neutral-900 group-hover:text-brand-500 transition-colors mb-1">{fylke.navn}</h2><p className="text-body-sm text-neutral-500 mb-3 clamp-2">{fylke.kortTekst}</p><div className="text-caption text-neutral-400">{fylke.innbyggere.toLocaleString("nb-NO")} innbyggere</div></div><ArrowUpRight className="w-5 h-5 text-neutral-300 group-hover:text-brand-500 transition-colors flex-shrink-0 mt-1" /></div></Link>))}</div></div></section><section className="section-py-sm"><div className="container-site"><div className="cta-block text-center relative z-10"><h2 className="font-display font-extrabold text-display-lg text-white mb-3">Finner du ikke kommunen din?</h2><p className="text-base text-neutral-500 mb-6">Vi dekker hele Norge. Fyll ut skjemaet og vi finner firma nær deg.</p><Link href="/kontakt" className="btn-primary">Få gratis tilbud <ArrowRight className="w-4 h-4" /></Link></div></div></section></main><Footer /><StickyMobileCTA /></>);
}
